# Generated by Django 3.2.5 on 2021-07-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlay',
            name='summa',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
