# Generated by Django 3.2.5 on 2021-07-24 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0002_outlay_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='outlay.outlaycategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='outlay',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='outlay',
            name='summa',
            field=models.FloatField(verbose_name='Сумма'),
        ),
    ]
