# Generated by Django 3.2.5 on 2021-07-24 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0003_auto_20210724_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlay',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 8, 22, 37, 873527)),
        ),
    ]
