# Generated by Django 3.2.5 on 2021-07-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0021_alter_outlay_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlay.outlaycategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='outlay',
            name='created',
            field=models.DateTimeField(default='2021-07-28'),
        ),
    ]
