# Generated by Django 3.2.5 on 2021-07-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SaunaPriceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sauna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sauna.sauna')),
            ],
        ),
    ]
