# Generated by Django 3.2.5 on 2021-07-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sauna',
            options={'verbose_name': 'Сауна', 'verbose_name_plural': 'Сауна'},
        ),
        migrations.AlterModelOptions(
            name='saunapricetypes',
            options={'verbose_name': 'Сауна цена', 'verbose_name_plural': 'Сауна цена'},
        ),
    ]
