# Generated by Django 3.2.5 on 2021-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0002_auto_20210719_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauna',
            name='color',
            field=models.CharField(choices=[('red', 'красный'), ('yellow', 'Желтый'), ('blue', 'Синий'), ('green', 'Зеленый'), ('pink', 'Розовый')], default='yellow', max_length=200),
        ),
    ]
