# Generated by Django 3.2.5 on 2021-07-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0003_sauna_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauna',
            name='color',
            field=models.CharField(choices=[('red', 'красный'), ('yellow', 'Желтый'), ('blue', 'Синий'), ('green', 'Зеленый'), ('pink', 'Розовый')], default='yellow', max_length=200, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Сауна'),
        ),
        migrations.AlterField(
            model_name='sauna',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=500, verbose_name='Сауна статус'),
        ),
        migrations.AlterField(
            model_name='saunapricetypes',
            name='max_people',
            field=models.IntegerField(verbose_name='Макс. человек'),
        ),
        migrations.AlterField(
            model_name='saunapricetypes',
            name='min_people',
            field=models.IntegerField(verbose_name='Мин. человек'),
        ),
        migrations.AlterField(
            model_name='saunapricetypes',
            name='price',
            field=models.IntegerField(verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='saunapricetypes',
            name='sauna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sauna.sauna', verbose_name='Сауна'),
        ),
    ]
