# Generated by Django 3.2.5 on 2021-07-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0004_auto_20210725_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saunapricetypes',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
