# Generated by Django 3.2.5 on 2021-07-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('regular', 'Постоянный'), ('normal', 'Обычный'), ('vip', 'VIP')], default='normal', max_length=500, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='content',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=500, verbose_name='Статус'),
        ),
    ]
