# Generated by Django 3.2.5 on 2021-07-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210717_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default=None, max_length=500, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
