# Generated by Django 3.2.5 on 2021-07-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210717_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('regular', 'Постоянный'), ('normal', 'Обычный'), ('vip', 'VIP')], default='normal', max_length=500, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=500, verbose_name='Статус'),
        ),
    ]
