# Generated by Django 3.2.5 on 2021-07-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0003_paymentlog_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='discount',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
