# Generated by Django 3.2.5 on 2021-07-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0004_paymentlog_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
