# Generated by Django 3.2.5 on 2021-07-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0007_alter_paymentlog_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличный расчет'), ('cashless', 'Безналичный расчет')], default='cash', max_length=500, verbose_name='Метод'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_type',
            field=models.CharField(choices=[('payment', 'Оплата'), ('advance', 'Аванс')], default='advance', max_length=500, verbose_name='Тип'),
        ),
    ]
