# Generated by Django 3.2.5 on 2021-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0008_auto_20210724_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='total',
            field=models.IntegerField(),
        ),
    ]
