# Generated by Django 3.2.5 on 2021-07-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0009_alter_paymentlog_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
