# Generated by Django 3.2.5 on 2021-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0010_alter_paymentlog_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
