# Generated by Django 3.2.5 on 2021-07-25 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_order_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentlog', '0011_alter_paymentlog_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
