# Generated by Django 3.2.5 on 2021-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0012_auto_20210725_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='created',
            field=models.DateTimeField(default='2021-07-25'),
        ),
    ]
