# Generated by Django 3.2.5 on 2021-07-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0014_alter_paymentlog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='created',
            field=models.DateTimeField(default='2021-07-28', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличный расчет'), ('cashless', 'Безналичный расчет')], default='cash', max_length=500, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_type',
            field=models.CharField(choices=[('payment', 'Оплата'), ('advance', 'Аванс')], default='advance', max_length=500, verbose_name='Тип оплаты'),
        ),
    ]
