# Generated by Django 3.2.5 on 2021-07-29 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentlog', '0016_alter_paymentlog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='created',
            field=models.DateTimeField(default=datetime.date(2021, 7, 29), verbose_name='Дата создания'),
        ),
    ]
