# Generated by Django 3.2.5 on 2021-07-10 21:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('sauna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
                ('sauna_hour_price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('start_time', models.CharField(max_length=500)),
                ('end_time', models.CharField(max_length=500)),
                ('hours', models.IntegerField()),
                ('discount', models.FloatField()),
                ('status', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client.client')),
                ('sauna', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sauna.sauna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('count', models.FloatField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
    ]
