# Generated by Django 3.2.5 on 2021-07-16 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
        ('product', '0001_initial'),
        ('sauna', '0001_initial'),
        ('order', '0003_auto_20210716_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.IntegerField(verbose_name='Количество человека')),
                ('sauna_hour_price', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('start_time', models.CharField(max_length=500, verbose_name='Начало')),
                ('end_time', models.CharField(max_length=500, verbose_name='Конец')),
                ('hours', models.IntegerField(verbose_name='Время')),
                ('discount', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(choices=[('red', 'красный'), ('yellow', 'Желтый'), ('blue', 'Синий'), ('green', 'Зеленый'), ('pink', 'Розовый')], default='yellow', max_length=500, verbose_name='Цвет')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client.client', verbose_name='Клиент')),
                ('sauna', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sauna.sauna', verbose_name='Сауна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('count', models.FloatField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
    ]
