# Generated by Django 3.2.5 on 2021-07-25 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('red', 'красный'), ('yellow', 'Желтый'), ('blue', 'Синий'), ('green', 'Зеленый'), ('pink', 'Розовый')], default='yellow', max_length=500, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 5, 38, 26, 658072)),
        ),
    ]
