# Generated by Django 3.2.5 on 2021-07-26 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 15, 19, 24, 758215)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'в бронировании'), ('inactive', 'Неактивный')], default='active', max_length=500, verbose_name='Статус'),
        ),
    ]
